# Generated by Django 6.0 on 2025-12-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('ANALYST', 'Analyst')], default='OPERATOR', help_text='User role in the system', max_length=20, verbose_name='Role'),
        ),
    ]
