# Generated by Django 6.0 on 2026-01-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_alter_user_role'),
    ]

    operations = [
        # Add new event types to the Event model choices
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('ARRIVAL', 'Arrival'),
                    ('DEPARTURE', 'Departure'),
                    ('ANCHORAGE', 'Anchorage'),
                    ('BERTHING', 'Berthing'),
                    ('CARGO_OPERATION', 'Cargo Operation'),
                    ('INCIDENT', 'Incident'),
                    ('WEATHER_ALERT', 'Weather Alert'),
                    ('HIGH_CONGESTION', 'High Port Congestion'),
                    ('STORM_ENTRY', 'Storm Zone Entry'),
                    ('PIRACY_RISK', 'Piracy Risk Zone Entry'),
                    ('OTHER', 'Other'),
                ],
                max_length=50,
                verbose_name='Event Type'
            ),
        ),
        # Add new fields to Port model
        migrations.AddField(
            model_name='port',
            name='arrivals_count',
            field=models.IntegerField(
                default=0,
                help_text='Number of vessel arrivals',
                verbose_name='Arrivals Count'
            ),
        ),
        migrations.AddField(
            model_name='port',
            name='departures_count',
            field=models.IntegerField(
                default=0,
                help_text='Number of vessel departures',
                verbose_name='Departures Count'
            ),
        ),
        migrations.AddField(
            model_name='port',
            name='last_updated',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Last Updated'
            ),
        ),
    ]
