# Generated by Django 6.0 on 2026-01-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_event_types_only'),
    ]

    operations = [
        # Use a Python function to handle the column drop safely
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # Do nothing - the field should be handled by Django
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
