# Generated by Django 6.0 on 2026-01-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_port_last_update_field'),
    ]

    operations = [
        # Add MMSI field to Vessel model
        migrations.AddField(
            model_name='vessel',
            name='mmsi',
            field=models.CharField(
                blank=True,
                help_text='Maritime Mobile Service Identity',
                max_length=20,
                null=True,
                verbose_name='MMSI'
            ),
        ),
        # Add speed field to Vessel model
        migrations.AddField(
            model_name='vessel',
            name='speed',
            field=models.FloatField(
                blank=True,
                help_text='Speed in knots',
                null=True,
                verbose_name='Speed'
            ),
        ),
        # Add heading field to Vessel model
        migrations.AddField(
            model_name='vessel',
            name='heading',
            field=models.IntegerField(
                blank=True,
                help_text='Heading in degrees (0-359)',
                null=True,
                verbose_name='Heading'
            ),
        ),
    ]
