# Generated by Django 6.0 on 2026-01-08 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_vessel_ais_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(
                    choices=[
                        ('ALL_EVENTS', 'All Events'),
                        ('SAFETY_ONLY', 'Safety Events Only'),
                        ('POSITION_UPDATES', 'Position Updates Only'),
                        ('CUSTOM', 'Custom Events')
                    ],
                    default='ALL_EVENTS',
                    max_length=20,
                    verbose_name='Subscription Type'
                )),
                ('notify_storm_zones', models.BooleanField(default=True, verbose_name='Notify Storm Zone Entry')),
                ('notify_piracy_zones', models.BooleanField(default=True, verbose_name='Notify Piracy Zone Entry')),
                ('notify_congestion', models.BooleanField(default=True, verbose_name='Notify Congestion Risk')),
                ('notify_position_updates', models.BooleanField(default=False, verbose_name='Notify Position Updates')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vessel_subscriptions',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='User'
                )),
                ('vessel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='subscribers',
                    to='core.vessel',
                    verbose_name='Vessel'
                )),
            ],
            options={
                'verbose_name': 'Vessel Subscription',
                'verbose_name_plural': 'Vessel Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vesselsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'vessel'), name='unique_user_vessel_subscription'),
        ),
    ]
